### ISSUE TITLE
nosetests run fails with flask_testing

### ISSUE THREAD

**Issue by apolloclark** [lydiadwyer/sheparddb#1]
Unit tests are failing with flask_testing

``` shell
git clone https://github.com/lydiadwyer/sheparddb/ sheparddb-test
cd sheparddb-test
git checkout 738ddc840e4455b424568474d2e169b2e79065bc

vagrant up
vagrant ssh
sudo su -
cd /var/www/sheparddb/
export PYTHONPATH=$(pwd)
find . -name \*.pyc -delete
nosetests --with-xcoverage --cover-package=sheparddb \
    -q -x --verbosity=2 --cover-inclusive --no-byte-compile
```

the output:

``` raw
InvalidRequestError: Table 'artifacts' is already defined for this MetaData instance.  Specify 'extend_existing=True' to redefine options and columns on an existing Table object.
```

however, if you add "**table_args** = {"extend_existing": True}" to the models, the output:

``` raw
InvalidRequestError: Multiple classes found for path "City" in the registry of this declarative base. Please use a fully module-qualified path.

```

**Comment by jcomo** [comment]
Chiming in here. This isn't a flask testing issue. That exception appears to be coming from SQLAlchemy (more info: http://docs.sqlalchemy.org/en/latest/core/exceptions.html#sqlalchemy.exc.InvalidRequestError). Perhaps something is amiss with your imports or model schema configuration?

**Comment by apolloclark** [comment]
@jcomo awesome, thanks for looking at this. I rolled the repo back to an older version from 2 weeks ago, noticed that nosetests was being run with out "--cover-inclusive", that may be a source of the issue, and that we were using "setUp()" vs. "setUpClass()" in the unit test to initialize the app.
